### ISSUE TITLE
Handle dot character in key name which fails getter generation

### ISSUE THREAD

**Issue by om-ha** [localizely/intl_utils#85] opened 2022-07-01 14:50 UTC
As the title suggests, when a key contain dot character, getter generation fails and we get an error/warning:

https://github.com/localizely/intl_utils/blob/dd66c97f252c9dfb231ad03dd4ed87a4480900cc/lib/src/generator/label.dart#L401

It's because the key name does not conform to the regex `variableRegex`:
https://github.com/localizely/intl_utils/blob/dd66c97f252c9dfb231ad03dd4ed87a4480900cc/lib/src/generator/label.dart#L512

I created a pull-request to solve this issue https://github.com/localizely/intl_utils/pull/84

Could you please merge it? Otherwise we cannot use this library or we have to modify it and use it internally, losing future updates to this library.

**Comment by lzoran** [comment] 2022-07-08 17:13
Duplicate of [issue#15](https://github.com/localizely/flutter-intl-vscode/issues/15)

**Comment by lzoran** [comment] 2022-07-08 17:38
Closing this issue as a duplicate.

As said before, this would diverge from the official naming practices for Flutter internationalization. 

Also, this change would introduce inconsistency between the arb files and the generated localization code, which can make further localization work difficult. Maybe, it would be better to have separate action or script that would update such string keys than converting them automatically during generation.

**Closed by lzoran** 2022-07-08 17:38 UTC
Labels: duplicate
