### ISSUE TITLE
Parser fails to parse dart keywords

### ISSUE THREAD

**Issue by TarekTolba1** [localizely/intl_utils#123] opened 2024-04-17 03:41 UTC
Having `"break": "Break"` or `"continue": "Continue"` in the .arb files will throws an error while generating the messages.
```
INFO: Failed to format 'l10n.dart' file.
Error in parsing .../l10n.dart, no messages extracted.
ERROR: Failed to generate localization files./
Invalid argument(s): Parsing errors in .../l10n.dart
```

Yet, the files are successfully generated

**Comment by lzoran** [comment] 2024-04-17 08:33
I would say that this is expected, as `break` and `continue` are reserved keywords in Dart and can't be used as identifiers. Maybe prefixing such string key names with `common` or `general` would be the approach to go (e.g., `commonBreak`, `commonContinue`, `generalBreak`, `generalContinue`).


Duplicate of localizely/flutter-intl-vscode#91.

**Closed by lzoran** 2024-04-17 08:33 UTC
