### ISSUE TITLE
Tags within translated strings are removed in message_en.dart

### ISSUE THREAD

**Issue by calvin-verticalscope** [localizely/intl_utils#44] opened 2021-05-03 19:07 UTC
I have the following string in intl_en.arb "By continuing, you agree to our\n\<l\>Terms of Service\</l\> and \<l\>Privacy Policy\</l\>."

After I run flutter pub run intl_utils:generate, the string in message_en.dart becomes MessageLookupByLibrary.simpleMessage("By continuing, you agree to our\n").  

I can manually modify the string in simpleMessage by adding the rest of the line to get it to work. However, this wouldn't be a feasible long term work around. It used to generate fine.

Any idea what happened?

**Comment by calvin-verticalscope** [comment] 2021-05-03 19:40
Something I noticed just now is if the entire string was wrapped with a tag i.e. "\<t\>By continuing, you agree to our\n\<l\>Terms of Service\</l\> and \<l\>Privacy Policy\</l\>.\</t\>"

**Comment by lzoran** [comment] 2021-05-04 10:00
Hi @calvin-verticalscope,

Thanks for reporting this!

It seems that this issue appeared within the `intl_utils 2.2.0` (probably related to the last parse changes). We will try to release the fix for it in one of the upcoming releases.

In the meantime, you can use the `intl_utils 2.1.0` as an alternative.

**Comment by lzoran** [comment] 2021-07-14 15:49
Hi @calvin-verticalscope,

The issue is fixed with the latest version of the `intl_utils` package (`2.4.0`).

**Comment by aleksakrstic** [comment] 2021-07-15 18:50
I am closing this issue now.
In case of any new problems, please open a new issue.

**Closed by aleksakrstic** 2021-07-15 18:50 UTC
