### ISSUE TITLE
Feature request: Add --[no]-required-resource-attributes flag

### ISSUE THREAD

**Issue by t1r** [localizely/intl_utils#13] opened 2020-11-29 07:34 UTC
Hi, thank you for your plugin, it's a convenient tool.

Could you add support 
--[no]-required-resource-attributes 
flag, please.

From this:

https://github.com/flutter/flutter/pull/68774

PS: And for plugins too. thank you.

**Comment by aleksakrstic** [comment] 2020-12-01 11:12
Hi @t1r 
Thanks for opening this topic.
It seems gen_l10n tool decided to add this flag because resource attributes were required for that tool before.

For `intl_utils` they were not required.
Did you want to have a flag that forces resource attributes to be required?

I would keep this issue open for some time to see if it will get many upvotes.

**Comment by t1r** [comment] 2020-12-02 11:52
Hi @aleksakrstic 
>For intl_utils they were not required.

Hm, it's very strange, but in my case, I got error, when try generate strings without meta information, like this:
https://github.com/flutter/flutter/issues/67207

I'm use [idea plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl) + 
```
  intl_utils: ^1.9.0
flutter_intl:
  enabled: true
```

**Comment by aleksakrstic** [comment] 2020-12-02 21:45
Hi @t1r 
Do you maybe have `l10n.yaml` file in the root of the project? Asking because in that case that is an error from `gen_l10n` tool. And you should use either `gen_l10n` or `Flutter Intl` plugin, not both.

If that is not the case, could you paste here strings in ARB files for which you get such errors , so I can test them?

**Comment by t1r** [comment] 2020-12-22 10:45
Hi.
Sorry for the delayed response. 
I think the problem is in my project, but I haven’t found out the concrete reason (there is no l10n.yaml file in my old project). 
I created a new project and added the same dependencies and it’s working fine and doesn't require attributes.

**Comment by aleksakrstic** [comment] 2020-12-24 09:09
Hi @t1r 
Great that you solved it.
I will close this issue now, but in case you find out what was the cause, please share it here, so we can potentially improve it.

**Closed** 2020-12-24 09:57 UTC
