### ISSUE TITLE
Support nested translations 

### ISSUE THREAD

**Issue by Solano-Furlan** [localizely/intl_utils#89] opened 2022-09-09 14:52 UTC
It would be great if there was support for nested translations, this would be useful to organize the arb fils into features on large projects, could you add this feature?   

```
{
"feature1": {
        "text1": "text",
        "text2": "text"
    }, 
    "feature2": {
        "text1": "text",
        "text2": "text"
    }
}
```

**Comment by goranluledzija** [comment] 2022-09-11 17:21
Duplicate of https://github.com/localizely/intl_utils/issues/40

**Closed by goranluledzija** 2022-09-11 17:21 UTC
